# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PORT: 3000
  MONGODB_URL: mongodb://127.0.0.1:27017/express-mongo
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Check tests coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: "85"
        filename: "./coverage/clover.xml"
    
